services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - ${DB_LOCAL_PORT}:${DB_PORT}
    volumes:
      - local_portfolioDB:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
      POSTGRES_DB: ${DB_NAME} 

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    ports: 
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}

volumes:
  local_portfolioDB:
  pgadmin-data: